apiVersion: v1
appVersion: "1.0"
description: Beets - the media library management system for obsessive music geeks
name: beets
version: 0.2.2
icon: https://patrickjmcd.github.io/helm-charts/beets/logo/beets.png
