
replicaCount: 1

image:
  repository: linuxserver/beets
  tag: latest
  pullPolicy: IfNotPresent

uid: 1000
gid: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - beets.patrickjmcd.org
  tls:
   - secretName: beets-patrickjmcd-org
     hosts:
       - beets.patrickjmcd.org

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/beets"
  - name: myvolume
    mountPath: "/downloads"
    subPath: "downloads/music"
  - name: myvolume
    mountPath: "/music"
    subPath: "medias/music"

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 1Gi
    cpu: 2

nodeSelector: {}

tolerations: []

affinity: {}
