apiVersion: v1
appVersion: 1.5.1
description: A buddy for babies! Helps caregivers track sleep, feedings, diaper changes, tummy time and more to learn about and predict baby's needs without (as much) guess work.
name: babybuddy
version: 0.2.2
icon: https://patrickjmcd.github.io/helm-charts/babybuddy/logo/icon.png
