apiVersion: v1
kind: Service
metadata:
  name: {{ template "homebridge.fullname" . }}
  labels:
    app: {{ template "homebridge.name" . }}
    chart: {{ template "homebridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - name: homebridge
    port: 51827
    protocol: TCP
    targetPort: homebridge
  selector:
    app: {{ template "homebridge.name" . }}
    release: {{ .Release.Name }}
  externalIPs:
    - {{ .Values.loadbalancer_ip}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "homebridge.fullname" . }}-ui
  labels:
    app: {{ template "homebridge.name" . }}
    chart: {{ template "homebridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config_ui_port }}
      protocol: TCP
      name: homebridge-ui
  selector:
    app: {{ template "homebridge.name" . }}
    release: {{ .Release.Name }}
