{{- if .Values.gatewaybridge.enabled -}}
{{- if eq .Values.gatewaybridge.backendType "semtech_udp" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chirpstack.gatewaybridge.fullname" . }}-semtech
  labels:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
spec:
  type: {{ .Values.gatewaybridge.service.type | quote}}
  {{- if .Values.gatewaybridge.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gatewaybridge.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
  - name: "semtech"
    port: 1700
    protocol: UDP
    targetPort: 1700
  selector:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
{{- end -}}

{{ if eq .Values.gatewaybridge.backendType "basic_station" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chirpstack.gatewaybridge.fullname" . }}-basicstation
  labels:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
spec:
  type: {{ .Values.gatewaybridge.service.type | quote}}
  {{- if .Values.gatewaybridge.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gatewaybridge.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
  - name: "basicstation"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
{{- end -}}
{{- end -}}