{{- if .Values.gatewaybridge.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chirpstack.gatewaybridge.fullname" . }}-semtech
  labels:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
spec:
  type: {{ .Values.gatewaybridge.service.semtech.type | quote}}
  {{- if .Values.gatewaybridge.service.semtech.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gatewaybridge.service.semtech.loadBalancerIP | quote }}
  {{- end }}
  ports:
  - name: "semtech"
    port: 1700
    protocol: UDP
    targetPort: 1700
  selector:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chirpstack.gatewaybridge.fullname" . }}-basicstation
  labels:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
spec:
  type: {{ .Values.gatewaybridge.service.basicstation.type | quote}}
  {{- if .Values.gatewaybridge.service.basicstation.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gatewaybridge.service.basicstation.loadBalancerIP | quote }}
  {{- end }}
  ports:
  - name: "basicstation"
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
{{ include "chirpstack.gatewaybridge.labels" . | indent 4 }}
{{- end -}}